# Server
server:
  port: 80
  address: 127.0.0.1
  servlet:
    session:
      timeout: 6000


spring:
  devtools:
    restart:
      enabled: true
      
  messages.basename: i18n/messages
  
  datasource:
    name: "app"
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://192.168.0.31:3306/app?useSSL=false&characterEncoding=utf-8&useUnicode=true"
    username: "lwj"
    password: "lwj6TX006!"
    hikari:
      pool-name: "app-hikari-20"
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 10000
      validation-timeout: 4000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      
