# Server
server:
  port: 80
  servlet:
    session:
      timeout: 600
      
spring:
  messages.basename: i18n/messages
  
  datasource:
    name: "app"
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://192.168.0.31:3306/app?useSSL=false&characterEncoding=utf-8&useUnicode=true"
    username: "lwj"
    password: "lwj6TX006!"
    hikari:
      maximum-pool-size: 3
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      
